### ISSUE TITLE
where to download SemEval 2015 original data

### ISSUE THREAD

**Issue by xikakera** [Noahs-ARK/NeurboParser#2]
i can't find the dataset anywhere, can you get me a link?

**Comment by haopeng-nlp** [comment]
Hi, xikakera,

You can find more information here: http://sdp.delph-in.net, or on the shared task page: http://alt.qcri.org/semeval2015/task18/. 

Although the data is freely available, I don't think we have the right to redistribute it. I encourage you to contact the organizer, Stephan Oepen (oe@ifi.uio.no), to get the data.

**Comment by oepen** [comment]
part of the SDP 2015 data is freely available, indeed.  it can be downloaded from the SDP archive site at:

http://sdp.delph-in.net/index.php?page=5

however, for the multi-task learning approach, multiple english target representations may be needed.  some of the SDP graphs are derivative of the Penn Treebank and, thus, subject to licensing from the Linguistic Data Consortium (LDC).  the complete SDP 2015 data can be obtained only through the LDC; see:

https://catalog.ldc.upenn.edu/LDC2016T10

**Comment by Woodrow1026** [comment]
> part of the SDP 2015 data is freely available, indeed. it can be downloaded from the SDP archive site at:
> 
> http://sdp.delph-in.net/index.php?page=5
> 
> however, for the multi-task learning approach, multiple english target representations may be needed. some of the SDP graphs are derivative of the Penn Treebank and, thus, subject to licensing from the Linguistic Data Consortium (LDC). the complete SDP 2015 data can be obtained only through the LDC; see:
> 
> https://catalog.ldc.upenn.edu/LDC2016T10

I found DM is available in the first link.
but I'm not sure is there all the DM data is this link.
Maybe you can give me a answer?

**Comment by oepen** [comment]
> Maybe you can give me a answer?

the Open SDP package (free download from the first list) includes all the DM data from the SemEval 2014 and 2015 campaigns.
