### ISSUE TITLE
How can I prune the pretrained word embeddings?

### ISSUE THREAD

**Issue by ghost** [Noahs-ARK/NeurboParser#3]
The default filename of the pretrained word embeddings is "glove.100.pruned", but the file I downloaded from [GloVe](https://nlp.stanford.edu/projects/glove/) was "glove.6B.100d.txt"... Would mind letting us reuse your prune script, or letting us know your pruning steps and parameters?
Thanks.

**Comment by haopeng-nlp** [comment]
Hi, the embedding pruning just removes all the word vectors that do not appear in the training data, so that the loading part could be faster. So the original embedding file should work just fine.

**Comment by ghost** [comment]
Make sense. Thanks a lot ;)
